"""Add AI cache columns to resume

Revision ID: 84e43d96607b
Revises: c37de9b7972d
Create Date: 2026-09-23 21:59:44.547254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e43d96607b'
down_revision: Union[str, Sequence[str], None] = 'c37de9b7972d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('is_analyzed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('resumes', sa.Column('parsed_data', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('health_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'health_data')
    op.drop_column('resumes', 'parsed_data')
    op.drop_column('resumes', 'is_analyzed')
    # ### end Alembic commands ###
