"""Add performance indexes to foreign keys

Revision ID: aa3dea75205f
Revises: 84e43d96607b
Create Date: 2026-09-23 22:27:38.293344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3dea75205f'
down_revision: Union[str, Sequence[str], None] = '84e43d96607b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_educations_user_id_start_date', 'educations', ['user_id', 'start_date'], unique=False)
    op.create_index('ix_experiences_user_id_start_date', 'experiences', ['user_id', 'start_date'], unique=False)
    op.create_index('ix_projects_user_id_created_at', 'projects', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_resumes_user_id_is_analyzed', 'resumes', ['user_id', 'is_analyzed'], unique=False)
    op.create_index('ix_resumes_user_id_uploaded_at', 'resumes', ['user_id', 'uploaded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resumes_user_id_uploaded_at', table_name='resumes')
    op.drop_index('ix_resumes_user_id_is_analyzed', table_name='resumes')
    op.drop_index('ix_projects_user_id_created_at', table_name='projects')
    op.drop_index('ix_experiences_user_id_start_date', table_name='experiences')
    op.drop_index('ix_educations_user_id_start_date', table_name='educations')
    # ### end Alembic commands ###
