from datetime import timedelta
from typing import Any, Optional

async def verify_password(plain_password: str, hashed_password: str) -> bool: ...
async def get_password_hash(password: str) -> str: ...
def create_access_token(data: dict[str, Any], expires_delta: Optional[timedelta] = None) -> str: ...
def decode_access_token(token: str) -> Optional[dict[str, Any]]: ...
